export const WORLD_RADIUS = 58;

export const NEST_POSITION = { x: -26, z: 22, radius: 10 };
export const DANGER_ZONE = { x: 24, z: -18, radius: 18 };

export const PLAYER_BASE_STATS = {
  speed: 11.5,
  health: 120,
  biteDamage: 22,
  biteCooldown: 0.62,
  knockback: 1,
  defense: 0,
  intimidation: 0,
};

export const UPGRADE_DEFS = [
  {
    key: "jaw",
    label: "Crushing Jaw",
    slot: "Head",
    costs: [16, 28, 42],
    description: "Bigger bite profile and +7 damage per level",
  },
  {
    key: "horns",
    label: "Hook Horns",
    slot: "Head",
    costs: [18, 32],
    description: "+4 bite damage and stronger enemy intimidation",
  },
  {
    key: "crest",
    label: "Sunspine Crest",
    slot: "Back",
    costs: [14, 24],
    description: "Radiant dorsal frill that pushes scavengers off your line",
  },
  {
    key: "tail",
    label: "Whip Tail",
    slot: "Tail",
    costs: [16, 28],
    description: "+18% knockback and sharper strike follow-through",
  },
  {
    key: "legs",
    label: "Stilt Legs",
    slot: "Legs",
    costs: [18, 30, 46],
    description: "+10% movement speed and taller stride",
  },
  {
    key: "spikes",
    label: "Rib Spikes",
    slot: "Body",
    costs: [18, 32, 46],
    description: "+16 max health and +9% defense per level",
  },
  {
    key: "glow",
    label: "Glow Veins",
    slot: "Markings",
    costs: [14, 26, 38],
    description: "-8% bite recovery and brighter bioluminescent markings",
  },
];

export const FOOD_SPAWNS = [
  { x: -20, z: 9, dna: 3, rare: false },
  { x: -12, z: 14, dna: 3, rare: false },
  { x: -4, z: 5, dna: 3, rare: false },
  { x: 2, z: 14, dna: 3, rare: false },
  { x: 10, z: 4, dna: 4, rare: false },
  { x: 15, z: 17, dna: 4, rare: false },
  { x: -17, z: 30, dna: 4, rare: false },
  { x: -6, z: 31, dna: 3, rare: false },
  { x: 11, z: 29, dna: 4, rare: false },
  { x: 20, z: 24, dna: 4, rare: false },
  { x: 29, z: 11, dna: 4, rare: false },
  { x: -27, z: -1, dna: 3, rare: false },
  { x: -16, z: -13, dna: 4, rare: false },
  { x: -4, z: -17, dna: 4, rare: false },
  { x: 6, z: -10, dna: 4, rare: false },
  { x: 18, z: -5, dna: 5, rare: true },
  { x: 25, z: -7, dna: 6, rare: true },
  { x: 31, z: -15, dna: 6, rare: true },
  { x: 36, z: -22, dna: 6, rare: true },
  { x: 16, z: -27, dna: 6, rare: true },
  { x: 22, z: -31, dna: 7, rare: true },
  { x: 30, z: -34, dna: 7, rare: true },
];

export const SCAVENGER_SPAWNS = [
  { x: -10, z: -2, enemyType: "scavenger" },
  { x: 6, z: 7, enemyType: "scavenger" },
  { x: 19, z: 18, enemyType: "armoredScavenger" },
  { x: -19, z: -18, enemyType: "scavenger" },
];

export const PREDATOR_SPAWNS = [
  { x: 18, z: -18, enemyType: "predator" },
  { x: 29, z: -25, enemyType: "hornedPredator" },
  { x: 34, z: -11, enemyType: "predator" },
];

export const ENEMY_DEFS = {
  scavenger: {
    label: "scavenger",
    family: "scavenger",
    color: 0xa88b68,
    accent: 0xefe2b5,
    speed: 8.8,
    health: 44,
    damage: 9,
    reward: 9,
    aggroRadius: 9,
    leashRadius: 13,
    attackRange: 2.4,
    scale: 0.95,
    yOffset: 1.3,
    traits: { jaw: 0, horns: 0, crest: 0, tail: 0, legs: 0, spikes: 0, glow: 0 },
    patternBias: 0,
    poise: 0.9,
  },
  armoredScavenger: {
    label: "armored scavenger",
    family: "scavenger",
    color: 0x917258,
    accent: 0xf4c98d,
    speed: 8.1,
    health: 60,
    damage: 10,
    reward: 12,
    aggroRadius: 10,
    leashRadius: 14,
    attackRange: 2.5,
    scale: 1.04,
    yOffset: 1.34,
    traits: { jaw: 1, horns: 0, crest: 1, tail: 1, legs: 0, spikes: 2, glow: 0 },
    patternBias: 1,
    poise: 1.25,
  },
  predator: {
    label: "predator",
    family: "predator",
    color: 0x6f503c,
    accent: 0xff8d5c,
    speed: 11.8,
    health: 92,
    damage: 18,
    reward: 18,
    aggroRadius: 16,
    leashRadius: 22,
    attackRange: 3.1,
    scale: 1.35,
    yOffset: 1.5,
    traits: { jaw: 1, horns: 0, crest: 1, tail: 1, legs: 1, spikes: 0, glow: 0 },
    patternBias: 2,
    poise: 1.55,
  },
  hornedPredator: {
    label: "horned predator",
    family: "predator",
    color: 0x604231,
    accent: 0xffb268,
    speed: 12.4,
    health: 104,
    damage: 22,
    reward: 24,
    aggroRadius: 18,
    leashRadius: 24,
    attackRange: 3.35,
    scale: 1.46,
    yOffset: 1.58,
    traits: { jaw: 2, horns: 2, crest: 1, tail: 1, legs: 1, spikes: 1, glow: 1 },
    patternBias: 0,
    poise: 1.8,
  },
};
