export const WORLD_RADIUS = 58;

export const NEST_POSITION = { x: -26, z: 22, radius: 10 };
export const DANGER_ZONE = { x: 24, z: -18, radius: 18 };
export const ORIGIN_POOL = {
  x: -34,
  z: 22,
  radius: 13,
  surfaceY: -1.1,
  spawnX: -39,
  spawnZ: 25,
};
export const SHALLOWS_ZONE = { x: -16, z: 18, radius: 19 };
export const MARSH_ZONE = { x: -8, z: 30, radius: 15 };
export const SALT_FLATS_ZONE = { x: -30, z: -23, radius: 16 };
export const EMBER_RIDGE_ZONE = { x: 31, z: 27, radius: 15 };

export const BIOME_DEFS = {
  originWaters: {
    key: "originWaters",
    label: "Origin Waters",
    shortLabel: "Origin",
    summary: "Universal cradle water. Newborn bodies grow fastest here.",
    pressure: "Safe nursery",
    uiColor: 0x7fe8dc,
    speed: 0.96,
    traction: 0.94,
    dust: 0.18,
    dnaMultiplier: 0.9,
    masteryRate: 0.95,
    newbornMasteryRate: 2.4,
    water: true,
    order: 0,
    unlockHint: "All species begin here.",
  },
  sunlitShallows: {
    key: "sunlitShallows",
    label: "Sunlit Shallows",
    shortLabel: "Shallows",
    summary: "Food-rich shallows where early lines learn to glide beyond the nursery.",
    pressure: "Starter frontier",
    uiColor: 0xa2efd4,
    speed: 1.02,
    traction: 0.96,
    dust: 0.34,
    dnaMultiplier: 1,
    masteryRate: 1.05,
    newbornMasteryRate: 1.8,
    water: true,
    order: 1,
    unlockHint: "Starter frontier",
  },
  glowMarsh: {
    key: "glowMarsh",
    label: "Glow Marsh",
    shortLabel: "Marsh",
    summary: "Sticky glow-mud, calmer prey lines, and softer ground that rewards patience.",
    pressure: "Adaptive frontier",
    uiColor: 0x88ffd6,
    speed: 0.9,
    traction: 0.82,
    dust: 0.26,
    dnaMultiplier: 1.1,
    masteryRate: 1.08,
    newbornMasteryRate: 1.3,
    water: false,
    order: 2,
    unlockHint: "Reach 6 XP or befriend Burrowing Herbivores",
  },
  boneDunes: {
    key: "boneDunes",
    label: "Bone Dunes",
    shortLabel: "Dunes",
    summary: "Open sand and long sightlines. Fast hunting, exposed migrations, and territorial fights.",
    pressure: "Expansion frontier",
    uiColor: 0xf0c28c,
    speed: 1.05,
    traction: 0.94,
    dust: 1,
    dnaMultiplier: 1.05,
    masteryRate: 1.1,
    newbornMasteryRate: 0.9,
    water: false,
    order: 3,
    unlockHint: "Raise a body past adolescent or reach 8 XP",
  },
  saltFlats: {
    key: "saltFlats",
    label: "Salt Flats",
    shortLabel: "Flats",
    summary: "Wind-burnished hardpan where runners and gliders cross fast but stay exposed.",
    pressure: "Runner frontier",
    uiColor: 0xe4f0df,
    speed: 1.12,
    traction: 1.08,
    dust: 0.44,
    dnaMultiplier: 1.12,
    masteryRate: 1.14,
    newbornMasteryRate: 0.72,
    water: false,
    order: 4,
    unlockHint: "Reach 14 XP, master Bone Dunes (12), or evolve a true runner.",
  },
  jawBasin: {
    key: "jawBasin",
    label: "Jaw Basin",
    shortLabel: "Basin",
    summary: "Predator basin where heavy DNA rewards come with relentless territorial pressure.",
    pressure: "War frontier",
    uiColor: 0xff8b66,
    speed: 0.97,
    traction: 0.86,
    dust: 0.82,
    dnaMultiplier: 1.15,
    masteryRate: 1.18,
    newbornMasteryRate: 0.55,
    water: false,
    order: 5,
    unlockHint: "Reach 18 XP or draw Bone Stalkers into open war",
  },
  emberRidge: {
    key: "emberRidge",
    label: "Ember Ridge",
    shortLabel: "Ridge",
    summary: "Raised basalt and ember vents where heavy bodies win short violent fights.",
    pressure: "Apex frontier",
    uiColor: 0xff9f78,
    speed: 0.94,
    traction: 1.03,
    dust: 0.92,
    dnaMultiplier: 1.2,
    masteryRate: 1.22,
    newbornMasteryRate: 0.46,
    water: false,
    order: 6,
    unlockHint: "Reach 26 XP, master Jaw Basin (14), or become a true bruiser.",
  },
};

export const PLAYER_BASE_STATS = {
  speed: 11.5,
  health: 120,
  biteDamage: 22,
  biteCooldown: 0.62,
  knockback: 1,
  defense: 0,
  intimidation: 0,
};

export const UPGRADE_DEFS = [
  {
    key: "jaw",
    label: "Crushing Jaw",
    slot: "Head",
    costs: [16, 28, 42],
    description: "Bigger bite profile and +7 damage per level",
    unlock: { type: "starter" },
  },
  {
    key: "horns",
    label: "Hook Horns",
    slot: "Head",
    costs: [18, 32],
    description: "+4 bite damage and stronger enemy intimidation",
    unlock: { type: "alpha", speciesId: "boneStalker" },
    unlockRoutes: [
      { type: "alpha", speciesId: "boneStalker" },
      { type: "frontier", biomeKey: "emberRidge", mastery: 14 },
    ],
  },
  {
    key: "crest",
    label: "Sunspine Crest",
    slot: "Back",
    costs: [14, 24],
    description: "Radiant dorsal frill that pushes scavengers off your line",
    unlock: { type: "ally", speciesId: "duneScavenger" },
    unlockRoutes: [
      { type: "ally", speciesId: "duneScavenger" },
      { type: "frontier", biomeKey: "sunlitShallows", mastery: 20 },
    ],
  },
  {
    key: "tail",
    label: "Long Whiptail",
    slot: "Tail",
    costs: [14, 24, 36],
    description: "Longer tail adds knockback, bite follow-through, and body control.",
    drawback: "Extra drag softens your launch and asks for a longer growth cycle.",
    unlock: { type: "starter" },
  },
  {
    key: "legs",
    label: "Longstride Legs",
    slot: "Legs",
    costs: [18, 30, 46],
    description: "Longer legs raise chase speed, turning, and shoreline reach.",
    drawback: "Stiltier frames feel lighter in collisions and shove less body weight.",
    unlock: { type: "starter" },
  },
  {
    key: "arms",
    label: "Raking Arms",
    slot: "Forelimbs",
    costs: [16, 28, 42],
    description: "Forelimbs add strike control, bite reach, and heavier body checks.",
    drawback: "Heavier shoulders trim sprint speed and demand more growth time.",
    unlock: { type: "starter" },
  },
  {
    key: "wings",
    label: "Glider Wings",
    slot: "Wings",
    costs: [20, 34, 48],
    description: "Wing-fins improve glide, turning, and sprint efficiency across open ground.",
    drawback: "Lighter frames lose toughness and do less shoving on impact.",
    unlock: { type: "ally", speciesId: "tideSkimmer" },
    unlockRoutes: [
      { type: "ally", speciesId: "tideSkimmer" },
      { type: "frontier", biomeKey: "sunlitShallows", mastery: 18 },
    ],
  },
  {
    key: "spikes",
    label: "Rib Spikes",
    slot: "Body",
    costs: [18, 32, 46],
    description: "+16 max health and +9% defense per level",
    unlock: { type: "ally", speciesId: "boneStalker" },
    unlockRoutes: [
      { type: "ally", speciesId: "boneStalker" },
      { type: "frontier", biomeKey: "saltFlats", mastery: 15 },
    ],
  },
  {
    key: "glow",
    label: "Glow Veins",
    slot: "Markings",
    costs: [14, 26, 38],
    description: "-8% bite recovery and brighter bioluminescent markings",
    unlock: { type: "ally", speciesId: "burrowingHerbivore" },
    unlockRoutes: [
      { type: "ally", speciesId: "burrowingHerbivore" },
      { type: "frontier", biomeKey: "glowMarsh", mastery: 11 },
    ],
  },
];

export const FOOD_SPAWNS = [
  { x: -38, z: 24, dna: 2, rare: false },
  { x: -35, z: 17, dna: 2, rare: false },
  { x: -31, z: 27, dna: 2, rare: false },
  { x: -28, z: 17, dna: 3, rare: false },
  { x: -20, z: 9, dna: 3, rare: false },
  { x: -12, z: 14, dna: 3, rare: false },
  { x: -4, z: 5, dna: 3, rare: false },
  { x: 2, z: 14, dna: 3, rare: false },
  { x: 10, z: 4, dna: 4, rare: false },
  { x: 15, z: 17, dna: 4, rare: false },
  { x: -17, z: 30, dna: 4, rare: false },
  { x: -6, z: 31, dna: 3, rare: false },
  { x: 11, z: 29, dna: 4, rare: false },
  { x: 20, z: 24, dna: 4, rare: false },
  { x: 29, z: 11, dna: 4, rare: false },
  { x: -27, z: -1, dna: 3, rare: false },
  { x: -16, z: -13, dna: 4, rare: false },
  { x: -32, z: -18, dna: 4, rare: false },
  { x: -36, z: -26, dna: 5, rare: true },
  { x: -24, z: -31, dna: 6, rare: true },
  { x: -4, z: -17, dna: 4, rare: false },
  { x: 6, z: -10, dna: 4, rare: false },
  { x: 18, z: -5, dna: 5, rare: true },
  { x: 25, z: -7, dna: 6, rare: true },
  { x: 31, z: -15, dna: 6, rare: true },
  { x: 24, z: 30, dna: 5, rare: true },
  { x: 31, z: 34, dna: 6, rare: true },
  { x: 38, z: 25, dna: 6, rare: true },
  { x: 36, z: -22, dna: 6, rare: true },
  { x: 16, z: -27, dna: 6, rare: true },
  { x: 22, z: -31, dna: 7, rare: true },
  { x: 30, z: -34, dna: 7, rare: true },
];

export const SCAVENGER_SPAWNS = [
  { x: -10, z: -2, enemyType: "scavenger" },
  { x: 6, z: 7, enemyType: "scavenger" },
  { x: 19, z: 18, enemyType: "armoredScavenger" },
  { x: -19, z: -18, enemyType: "scavenger" },
];

export const PREDATOR_SPAWNS = [
  { x: 18, z: -18, enemyType: "predator" },
  { x: 29, z: -25, enemyType: "hornedPredator" },
  { x: 34, z: -11, enemyType: "predator" },
];

export const ENEMY_DEFS = {
  tideSkimmer: {
    label: "tide skimmer",
    family: "herbivore",
    color: 0x72a8a0,
    accent: 0x92ffe1,
    speed: 9.8,
    health: 30,
    damage: 5,
    reward: 6,
    aggroRadius: 7,
    leashRadius: 16,
    attackRange: 2,
    scale: 0.84,
    yOffset: 1.08,
    traits: { jaw: 0, horns: 0, crest: 1, tail: 1, legs: 0, arms: 0, wings: 1, spikes: 0, glow: 0 },
    patternBias: 2,
    poise: 0.66,
  },
  scavenger: {
    label: "scavenger",
    family: "scavenger",
    color: 0xa88b68,
    accent: 0xefe2b5,
    speed: 8.8,
    health: 44,
    damage: 9,
    reward: 9,
    aggroRadius: 9,
    leashRadius: 13,
    attackRange: 2.4,
    scale: 0.95,
    yOffset: 1.3,
    traits: { jaw: 0, horns: 0, crest: 0, tail: 0, legs: 0, arms: 1, wings: 0, spikes: 0, glow: 0 },
    patternBias: 0,
    poise: 0.9,
  },
  armoredScavenger: {
    label: "armored scavenger",
    family: "scavenger",
    color: 0x917258,
    accent: 0xf4c98d,
    speed: 8.1,
    health: 60,
    damage: 10,
    reward: 12,
    aggroRadius: 10,
    leashRadius: 14,
    attackRange: 2.5,
    scale: 1.04,
    yOffset: 1.34,
    traits: { jaw: 1, horns: 0, crest: 1, tail: 1, legs: 0, arms: 1, wings: 0, spikes: 2, glow: 0 },
    patternBias: 1,
    poise: 1.25,
  },
  predator: {
    label: "predator",
    family: "predator",
    color: 0x6f503c,
    accent: 0xff8d5c,
    speed: 11.8,
    health: 92,
    damage: 18,
    reward: 18,
    aggroRadius: 16,
    leashRadius: 22,
    attackRange: 3.1,
    scale: 1.35,
    yOffset: 1.5,
    traits: { jaw: 1, horns: 0, crest: 1, tail: 1, legs: 1, arms: 1, wings: 0, spikes: 0, glow: 0 },
    patternBias: 2,
    poise: 1.55,
  },
  hornedPredator: {
    label: "horned predator",
    family: "predator",
    color: 0x604231,
    accent: 0xffb268,
    speed: 12.4,
    health: 104,
    damage: 22,
    reward: 24,
    aggroRadius: 18,
    leashRadius: 24,
    attackRange: 3.35,
    scale: 1.46,
    yOffset: 1.58,
    traits: { jaw: 2, horns: 2, crest: 1, tail: 1, legs: 1, arms: 1, wings: 0, spikes: 1, glow: 1 },
    patternBias: 0,
    poise: 1.8,
  },
  burrowingHerbivore: {
    label: "burrowing herbivore",
    family: "herbivore",
    color: 0xa69562,
    accent: 0x91ffe0,
    speed: 9.3,
    health: 34,
    damage: 6,
    reward: 7,
    aggroRadius: 8,
    leashRadius: 18,
    attackRange: 2.1,
    scale: 0.88,
    yOffset: 1.22,
    traits: { jaw: 0, horns: 0, crest: 0, tail: 0, legs: 1, arms: 1, wings: 0, spikes: 0, glow: 1 },
    patternBias: 1,
    poise: 0.72,
  },
};

export const SPECIES_DEFS = {
  tideSkimmer: {
    id: "tideSkimmer",
    name: "Tide Skimmer",
    temperament: "Curious",
    dietType: "grazer",
    aggression: 0.12,
    socialPattern: ["sing", "pose"],
    socialPrompt: "Answer with a bright trill, then glide in formation.",
    allyUnlocks: ["tail"],
    alphaUnlocks: [],
    packSize: [3, 4],
    uiColor: 0x8bf7e1,
    territory: {
      label: "Sun Shelf",
      x: -23,
      z: 18,
      radius: 14,
      color: 0x86e8d6,
      landmark: "reef",
    },
    nest: {
      x: -25,
      z: 17,
      hp: 95,
      type: "reef",
    },
    memberTypes: ["tideSkimmer"],
    spawnGroups: [
      { x: -30, z: 22, count: 2, leaderVariant: "tideSkimmer" },
      { x: -20, z: 12, count: 2, leaderVariant: "tideSkimmer" },
    ],
    respawnDelay: 13,
    maxPopulation: 4,
  },
  duneScavenger: {
    id: "duneScavenger",
    name: "Dune Scavenger",
    temperament: "Opportunistic",
    dietType: "scavenger",
    aggression: 0.56,
    socialPattern: ["pose", "charm"],
    socialPrompt: "Mirror their swagger, then soften the posture.",
    allyUnlocks: ["crest"],
    alphaUnlocks: ["tail"],
    packSize: [2, 3],
    uiColor: 0xf2d7a2,
    territory: {
      label: "Tidebone Shelf",
      x: 4,
      z: 8,
      radius: 17,
      color: 0xf0c08b,
      landmark: "scrap",
    },
    nest: {
      x: 7,
      z: 10,
      hp: 120,
      type: "scrap",
    },
    memberTypes: ["scavenger", "armoredScavenger"],
    spawnGroups: [
      { x: -10, z: -2, count: 2, leaderVariant: "scavenger" },
      { x: 16, z: 15, count: 2, leaderVariant: "armoredScavenger" },
    ],
    respawnDelay: 17,
    maxPopulation: 4,
  },
  boneStalker: {
    id: "boneStalker",
    name: "Bone Stalker",
    temperament: "Territorial",
    dietType: "predator",
    aggression: 0.86,
    socialPattern: ["pose", "sing"],
    socialPrompt: "Stand tall, then answer with a low bone-hum.",
    allyUnlocks: ["spikes"],
    alphaUnlocks: ["horns"],
    packSize: [1, 2],
    uiColor: 0xff9b72,
    territory: {
      label: "Jaw Basin",
      x: 26,
      z: -18,
      radius: 22,
      color: 0xff7c57,
      landmark: "spire",
    },
    nest: {
      x: 29,
      z: -21,
      hp: 165,
      type: "boneDen",
    },
    memberTypes: ["predator", "hornedPredator"],
    spawnGroups: [
      { x: 18, z: -18, count: 1, leaderVariant: "predator" },
      { x: 29, z: -25, count: 1, leaderVariant: "hornedPredator" },
      { x: 34, z: -11, count: 1, leaderVariant: "predator" },
    ],
    respawnDelay: 20,
    maxPopulation: 3,
  },
  burrowingHerbivore: {
    id: "burrowingHerbivore",
    name: "Burrowing Herbivore",
    temperament: "Skittish",
    dietType: "herbivore",
    aggression: 0.2,
    socialPattern: ["sing", "charm"],
    socialPrompt: "Start with a soft trill, then glow peacefully.",
    allyUnlocks: ["glow"],
    alphaUnlocks: [],
    packSize: [3, 4],
    uiColor: 0x96ffe3,
    territory: {
      label: "Glow Marsh",
      x: -8,
      z: 29,
      radius: 16,
      color: 0x7cf5d4,
      landmark: "burrow",
    },
    nest: {
      x: -7,
      z: 31,
      hp: 105,
      type: "burrow",
    },
    memberTypes: ["burrowingHerbivore"],
    spawnGroups: [
      { x: -15, z: 24, count: 2, leaderVariant: "burrowingHerbivore" },
      { x: -1, z: 32, count: 2, leaderVariant: "burrowingHerbivore" },
    ],
    respawnDelay: 15,
    maxPopulation: 4,
  },
};

export const MIGRATION_EVENT_DEFS = [
  {
    key: "tidalSkim",
    label: "Tidal Skim",
    speciesId: "tideSkimmer",
    duration: 14,
    cooldown: 24,
    target: { x: -7, z: 18 },
  },
  {
    key: "herdCrossing",
    label: "Herd Crossing",
    speciesId: "burrowingHerbivore",
    duration: 16,
    cooldown: 24,
    target: { x: 32, z: 14 },
  },
  {
    key: "stalkerRaid",
    label: "Stalker Raid",
    speciesId: "boneStalker",
    duration: 15,
    cooldown: 28,
    target: { x: -6, z: 24 },
  },
  {
    key: "scavengerSwarm",
    label: "Scavenger Swarm",
    speciesId: "duneScavenger",
    duration: 14,
    cooldown: 22,
    target: { x: 10, z: -2 },
  },
];
